baseURL = 'https://emoving-taichung.github.io/website/'
locale = "zh-TW"
title = 'eMOVING 精輪山西店｜台中電動機車'


[params]
  primaryColor = "#1155CC"
  backgroundColor = "#f9fcff"
  fontFamily = "Anybody"

# --- 記住：Hugo 設定檔中必須是單數的 menu.main ---
[[menu.main]]
  name = "首頁"
  url = "/website/"
  weight = 1

[[menu.main]]
  name = "主打優惠"
  url = "/website/promotions/"
  weight = 2

[[menu.main]]
  name = "最新消息"
  url = "/website/news/"
  weight = 3

[[menu.main]]
  name = "車款介紹"
  url = "/website/models/"
  weight = 4

[[menu.main]]
  name = "補助查詢"
  url = "/website/subsidy/"
  weight = 5

[[menu.main]]
  name = "門市據點"
  url = "/website/store/"
  weight = 6

[[menu.main]]
  name = "維修據點"
  url = "/website/maintenance/"
  weight = 7

[[menu.main]]
  name = "預約試乘"
  url = "/website/book-a-ride/"
  weight = 8

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true