baseURL = 'https://emoving-taichung.github.io/website/'
languageCode = "zh-TW"
locale = "zh-TW"
title = 'eMOVING 精輪山西店｜台中電動機車'

[params]
  primaryColor = "#1155CC"
  backgroundColor = "#f9fcff"
  fontFamily = "Anybody"

# 自動生成符合 SEO 規範的 Sitemap
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# --- 導覽列選單（使用根目錄相對路徑即可） ---
[[menu.main]]
  name = "首頁"
  url = "/"
  weight = 1

[[menu.main]]
  name = "主打優惠"
  url = "/promotions/"
  weight = 2

[[menu.main]]
  name = "最新消息"
  url = "/news/"
  weight = 3

[[menu.main]]
  name = "車款介紹"
  url = "/models/"
  weight = 4

[[menu.main]]
  name = "補助查詢"
  url = "/subsidy/"
  weight = 5

[[menu.main]]
  name = "門市據點"
  url = "/store/"
  weight = 6

[[menu.main]]
  name = "維修據點"
  url = "/maintenance/"
  weight = 7

[[menu.main]]
  name = "預約試乘"
  url = "/book-a-ride/"
  weight = 8

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true